### ISSUE TITLE
I tried adding project with different name but only projects are getting created with Same name & duplicate

### ISSUE THREAD

**Issue by sandip-more** [bvjogdand/sample_timesheet#2]
<img width="547" alt="screen shot 2019-01-23 at 6 47 23 pm" src="https://user-images.githubusercontent.com/23374948/51609166-61757880-1f3f-11e9-9078-776729a68b87.png">

**Comment by bvjogdand** [comment]
Fixed.
commit id: ac0959f37610561d4cede1cbc2f4b98da216d925
